name: Build Frontend

on: 
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm install
      - run: npm run build
      
  notify_on_success:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify cliq and email (success)
        run: |
          curl -X POST https://eoxcm5h1hcp250t.m.pipedream.net \
          -H "Content-Type: application/json" \
          -d '{
                "status": "${{ job.status }}",
                "branch": "${{ github.ref_name }}",
                "commit": "${{ github.sha }}",
                "workflow_name": "${{ github.workflow }}",
                "repository": "${{ github.repository }}",
                "run_id": "${{ github.run_id }}"
              }'
      
